### ISSUE TITLE
使用远程依赖会崩溃，崩溃日志显示找不到fastjson

### ISSUE THREAD

**Issue by ydmmocoo** [OpenIMSDK/Open-IM-SDK-Android#43]
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/alibaba/fastjson/JSONObject;
        at io.openim.android.sdk.utils.JsonUtil.toString(JsonUtil.java:9)
        at io.openim.android.sdk.OpenIMClient.initSDK(OpenIMClient.java:75)
        at io.openim.example.MainActivity.onCreate(MainActivity.java:44)
        at android.app.Activity.performCreate(Activity.java:7383)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3256)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3411)
        at android.app.ActivityThread.-wrap12(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1994)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7529)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.alibaba.fastjson.JSONObject" on path: DexPathList[[zip file "/data/app/io.openim.example-xUajOWjem03eSt1hrp6d6A==/base.apk"],nativeLibraryDirectories=[/data/app/io.openim.example-xUajOWjem03eSt1hrp6d6A==/lib/arm64, /data/app/io.openim.example-xUajOWjem03eSt1hrp6d6A==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /product/lib64, /preas/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at io.openim.android.sdk.utils.JsonUtil.toString(JsonUtil.java:9) 
        at io.openim.android.sdk.OpenIMClient.initSDK(OpenIMClient.java:75) 
        at io.openim.example.MainActivity.onCreate(MainActivity.java:44) 
        at android.app.Activity.performCreate(Activity.java:7383) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3256) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3411) 
        at android.app.ActivityThread.-wrap12(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1994) 
        at android.os.Handler.dispatchMessage(Handler.java:108) 
        at android.os.Looper.loop(Looper.java:166) 
        at android.app.ActivityThread.main(ActivityThread.java:7529) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921) 
![微信截图_20220520153010](https://user-images.githubusercontent.com/16789867/169476885-c1f35266-a104-44ff-b366-161e46fecd61.png)

**Comment by hrxiang** [comment]
implementation 'com.alibaba:fastjson:1.1.72.android'
