### ISSUE TITLE
[BUG] 为什么sdk运行在android7.0系统的手机上会崩溃

### ISSUE THREAD

**Issue by wozaihu** [openimsdk/open-im-sdk-android#67]
### OpenIM Server Version

3.8.1

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

集成sdk后，运行项目到红米note4（android7.0）上直接崩溃，下载官方提供的demo 也是一样崩溃，同一份代码运行到android8.0系统的手机上就没问题。报错如下
io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/ZoneId;
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:69)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:760)
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/ZoneId;
	at com.alibaba.fastjson2.JSONWriter$Context.<clinit>(JSONWriter.java:1144)
	at com.alibaba.fastjson2.JSON$-CC.toJSONString(JSON.java:2222)
	at com.alibaba.fastjson2.JSONObject.toJSONString(JSONObject.java:1095)
	at io.openim.android.ouicore.net.bage.GsonHel.toJson(GsonHel.java:38)
	at io.openim.android.ouicore.update.UpdateApp.lambda$checkUpdate$0(UpdateApp.java:66)
	at io.openim.android.ouicore.update.UpdateApp$$ExternalSyntheticLambda0.apply(D8$$SyntheticClass)
	at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:57)
	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:54)
	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:38)
	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:48)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:35)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:608)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	... 6 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "java.time.ZoneId" on path: DexPathList[[zip file "/data/app/io.openim.android.demo-1/base.apk"],nativeLibraryDirectories=[/data/app/io.openim.android.demo-1/lib/arm64, /data/app/io.openim.android.demo-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:74)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 24 more

**Comment by JauneQ** [comment]
This error seems to be from sdk demo, it occurs when getting updated data. The error points to fastjson2. If you want to support devices below android api 26, you will probably refactor the demo to use other json libraries instand of fastjson2. As far as I know this is a bug in fastjson2. [See this issue](https://github.com/alibaba/fastjson2/issues/864)
