### ISSUE TITLE
It's callback failed when I tried to call the getUserInfo and sendMessage method. 

### ISSUE THREAD

**Issue by luodanian** [openimsdk/open-im-sdk-android#78]
### OpenIM Server Version

3.8l1

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

可以登录成功，但是获取用户信息和发送消息时报错了
获取用户信息报错：code：10005    error：error *errors.errorString not implement CodeError: call panic: runtime error: invalid memory address or nil pointer dereference.     error: recover: runtime error: invalid memory address or nil pointer dereference
发送消息报错：code:10006 error:
 Failed -  - java.lang.IllegalStateException: Unable to create a fetcher that supports: 
 java.lang.IllegalStateException: Unable to create a fetcher that supports: 
at coil.intercept.EngineInterceptor.fetch(EngineInterceptor.kt:160)
at coil.intercept.EngineInterceptor.execute(EngineInterceptor.kt:122)
at coil.intercept.EngineInterceptor.access$execute(EngineInterceptor.kt:41)
at coil.intercept.EngineInterceptor$intercept$2.invokeSuspend(EngineInterceptor.kt:75)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

### Screenshots Link

 获取用户信息报错：code：10005    error：error *errors.errorString not implement CodeError: call panic: runtime error: invalid memory address or nil pointer dereference.     error: recover: runtime error: invalid memory address or nil pointer dereference
发送消息报错：code:10006 error:

Failed -  - java.lang.IllegalStateException: Unable to create a fetcher that supports: 
java.lang.IllegalStateException: Unable to create a fetcher that supports: 
at coil.intercept.EngineInterceptor.fetch(EngineInterceptor.kt:160)
at coil.intercept.EngineInterceptor.execute(EngineInterceptor.kt:122)
at coil.intercept.EngineInterceptor.access$execute(EngineInterceptor.kt:41)
 at coil.intercept.EngineInterceptor$intercept$2.invokeSuspend(EngineInterceptor.kt:75)
 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)

**Comment by JauneQ** [comment]
Please upload the full log information so that we can track the problem.

**Comment by JauneQ** [comment]
This issue has not been responded to for too long, we will close it after three days ago.
